interface ImportMetaEnv {
  NOTION_TOKENL: string;
  NOTION_EDUCATIONS_DATASOURCE: string;
  NOTION_TECH_STACK_DATASOURCE: string;
  NOTION_PROJECTS_DATASOURCE: string;
  NOTION_COMPANY_DATASOURCE: string;
  NOTION_TECHNICAL_DECISIONS_DATASOURCE: string;
  NOTION_TECH_STACK_TYPE_DATASOURCE: string;
  NOTION_PROJECT_BACKGROUND_DATASOURCE: string;
  NOTION_PROJECT_RESULT_DATASOURCE: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
